module.exports = [
    {
        trip_id: 1,
        item_id: 9,
        accounted_for: false,
        user_id: null,
        pending: null,
        shared: false,
        claimed_by: null,
    },
    {
        trip_id: 1,
        item_id: 16,
        accounted_for: false,
        user_id: null,
        pending: null,
        shared: false,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 61,
        accounted_for: false,
        user_id: null,
        pending: null,
        shared: false,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 63,
        accounted_for: false,
        user_id: null,
        pending: null,
        shared: false,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 67,
        accounted_for: false,
        user_id: null,
        pending: null,
        shared: false,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 64,
        accounted_for: false,
        user_id: null,
        pending: null,
        shared: false,
        claimed_by: null,
    },
]