module.exports = [
    {
        trip_id: 1,
        item_id: 1,
        accounted_for: false,
        user_id: 1,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 1,
        item_id: 2,
        accounted_for: false,
        user_id: 1,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 1,
        item_id: 3,
        accounted_for: false,
        user_id: 1,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 1,
        item_id: 4,
        accounted_for: false,
        user_id: 1,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 1,
        item_id: 5,
        accounted_for: false,
        user_id: 1,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 1,
        item_id: 7,
        accounted_for: false,
        user_id: 1,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 1,
        item_id: 10,
        accounted_for: false,
        user_id: 1,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 1,
        item_id: 1,
        accounted_for: false,
        user_id: 2,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 1,
        item_id: 2,
        accounted_for: false,
        user_id: 2,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 1,
        item_id: 3,
        accounted_for: false,
        user_id: 2,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 1,
        item_id: 4,
        accounted_for: false,
        user_id: 2,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 1,
        item_id: 5,
        accounted_for: false,
        user_id: 2,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 1,
        item_id: 7,
        accounted_for: false,
        user_id: 2,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 1,
        item_id: 10,
        accounted_for: false,
        user_id: 2,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 1,
        accounted_for: false,
        user_id: 1,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 2,
        accounted_for: false,
        user_id: 1,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 3,
        accounted_for: false,
        user_id: 1,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 1,
        accounted_for: false,
        user_id: 2,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 2,
        accounted_for: false,
        user_id: 2,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 3,
        accounted_for: false,
        user_id: 2,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 4,
        accounted_for: false,
        user_id: 1,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 4,
        accounted_for: false,
        user_id: 2,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 5,
        accounted_for: false,
        user_id: 2,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 5,
        accounted_for: false,
        user_id: 1,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 10,
        accounted_for: false,
        user_id: 1,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 10,
        accounted_for: false,
        user_id: 2,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 21,
        accounted_for: false,
        user_id: 2,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 21,
        accounted_for: false,
        user_id: 1,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 25,
        accounted_for: false,
        user_id: 2,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 25,
        accounted_for: false,
        user_id: 1,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 54,
        accounted_for: false,
        user_id: 2,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 54,
        accounted_for: false,
        user_id: 1,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 55,
        accounted_for: false,
        user_id: 2,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 55,
        accounted_for: false,
        user_id: 1,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 58,
        accounted_for: false,
        user_id: 2,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 58,
        accounted_for: false,
        user_id: 1,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 1,
        accounted_for: false,
        user_id: 8,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 2,
        accounted_for: false,
        user_id: 8,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 3,
        accounted_for: false,
        user_id: 8,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 4,
        accounted_for: false,
        user_id: 8,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 5,
        accounted_for: false,
        user_id: 8,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 10,
        accounted_for: false,
        user_id: 8,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 21,
        accounted_for: false,
        user_id: 8,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 25,
        accounted_for: false,
        user_id: 8,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 54,
        accounted_for: false,
        user_id: 8,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 55,
        accounted_for: false,
        user_id: 8,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 58,
        accounted_for: false,
        user_id: 8,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 1,
        accounted_for: false,
        user_id: 10,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 2,
        accounted_for: false,
        user_id: 10,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 3,
        accounted_for: false,
        user_id: 10,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 4,
        accounted_for: false,
        user_id: 10,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 5,
        accounted_for: false,
        user_id: 10,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 10,
        accounted_for: false,
        user_id: 10,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 21,
        accounted_for: false,
        user_id: 10,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 25,
        accounted_for: false,
        user_id: 10,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 54,
        accounted_for: false,
        user_id: 10,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 55,
        accounted_for: false,
        user_id: 10,
        pending: null,
        claimed_by: null,
    },
    {
        trip_id: 2,
        item_id: 58,
        accounted_for: false,
        user_id: 10,
        pending: null,
        claimed_by: null,
    },
]